<?php

/**
 * Implementation of hook_schema().
 */
function donl_dashboard_schema() {
  $schema = array();
  $schema['cache_donl_dashboard'] = drupal_get_schema_unprocessed('system', 'cache');
  return $schema;
}


/**
 * Add our own custom cache table for the dashboard
 */
function donl_dashboard_update_7001() {
  $schema = drupal_get_schema_unprocessed('system', 'cache');
  db_create_table('cache_donl_dashboard', $schema);
}