<?PHP
/**
 * Implementation of hook_form_FORM_ID_alter().
 */
function koop_overwrite_forgot_password_form_user_pass_alter(&$form, &$form_state) {
  unset($form['#validate']);
  $form['#submit'] = array('koop_overwrite_forgot_password_form_submit');
}


/**
 * Custom version of Drupal's user_pass_submit() function;
 * This is basically both user_pass_submit() and user_pass_validate() in one,
 * with the only difference being we'll never set an error.
 */
function koop_overwrite_forgot_password_form_submit($form, &$form_state) {
  global $language;

  $name = trim($form_state['values']['name']);

  // Try to load by email.
  $users = user_load_multiple(array(), array('mail' => $name, 'status' => '1'));
  $account = reset($users);
  if (!$account) {
    // No success, try to load by name.
    $users = user_load_multiple(array(), array('name' => $name, 'status' => '1'));
    $account = reset($users);
  }

  if (isset($account->uid)) {
    // Mail one time login URL and instructions using current language.
    $mail = _user_mail_notify('password_reset', $account, $language);
    if (!empty($mail)) {
      watchdog('user', 'Password reset instructions mailed to %name at %email.', array('%name' => $account->name, '%email' => $account->mail));
    }
  }

  drupal_set_message(t('Further instructions have been sent to your e-mail address if the given username or e-mail was known in our system.'));
  $form_state['redirect'] = 'user';
  return;
}